services:
  webservice:
    container_name: web
    build: ./docker/web
    ports:
      - "8765:8080"
    environment:
      DATABASE_URL: "postgresql://its:its@db:5432/its"
      IS_IN_DOCKER: "true"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - lt:/locationTest/

  location_test:
    container_name: lt
    build: ./docker/lt
    volumes:
      - lt:/locationTest/
    depends_on:
      webservice:
        condition: service_started


  db:
    container_name: db
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: its
      POSTGRES_PASSWORD: "its"
      POSTGRES_USER: "its"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U its"]
      interval: 2s
      timeout: 2s
      retries: 5
    volumes:
      - ./docker/db/its-pw/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - db:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:443"
    networks:
      - backend
    depends_on:
      webservice:
        condition: service_started
    volumes:
      - tcpdumpinfo:/tcpdumpinfo
  tcp:
    container_name: tcp
    build: ./docker/tcp
    volumes:
      - tcpdumpinfo:/tcpdumpinfo

networks:
  backend:

volumes:
  tcpdumpinfo:
  db:
  lt:
