services:
  webservice:
    container_name: web
    build: ./docker/web
    networks:
      - backend
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:443"
    networks:
      - backend

networks:
  backend:
