services:
  webservice:
    container_name: web
    build: ./docker/web
    networks:
      - backend
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8080:443"
    networks:
      - backend
    volumes:
      - tcpdumpinfo:/tcpdumpinfo
  tcp:
    container_name: tcp
    build: ./docker/tcp
    volumes:
      - tcpdumpinfo:/tcpdumpinfo

networks:
  backend:

volumes:
  tcpdumpinfo:
