FROM golang:1.24

# 2.4 Webservice
# RUN git clone --depth 1 https://github.com/Lars5Janssen/its-pw.git /webservice-go
# RUN cd /webservice-go && /usr/local/go/bin/go build -o /webservice-go/webservice /webservice-go/main.go
# RUN rm -rf /webservice-go

# BASIC
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y vim # FOR DEV

WORKDIR /usr/src/app/
COPY ./its-pw/go.mod ./its-pw/go.sum ./
RUN go mod download
ADD ./its-pw/ .
# RUN go build -v -o /usr/local/bin/app ./...
RUN go build -v .
RUN mv its-pw /usr/local/bin/app

CMD ["app"]
